---
apiVersion: v1
kind: Secret
metadata:
  name: smev-service-secret
  labels:
    app: smev-service
type: Opaque
stringData:
  SCHEMA_URL: "http://172.20.3.12:7500/smev/v1.2/ws"
  KEY_ALIAS: "KEY_ALIAS"
  KEY_PASSWORD: "11111111"
  KAFKA_ADDRESS: "kafka:9092"