package ru.it.smev.message_exchange.autogenerated.types.basic.v1_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "",
        propOrder = {"namespaceURI", "rootElementLocalName", "timestamp", "nodeID"}
)
@XmlRootElement(
        name = "MessageTypeSelector"
)
public class MessageTypeSelector {

    @XmlElement(
            name = "NamespaceURI"
    )
    @XmlSchemaType(
            name = "anyURI"
    )
    protected String namespaceURI;
    @XmlElement(
            name = "RootElementLocalName"
    )
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(
            name = "NCName"
    )
    protected String rootElementLocalName;
    @XmlElement(
            name = "Timestamp",
            required = true
    )
    @XmlSchemaType(
            name = "dateTime"
    )
    protected XMLGregorianCalendar timestamp;
    @XmlElement(
            name = "NodeID"
    )
    protected String nodeID;
    @XmlAttribute(
            name = "Id"
    )
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(
            name = "ID"
    )
    protected String id;

    // UNP attrs
    @XmlAttribute(
            name = "senderIdentifier"
    )
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(
            name = "senderIdentifier"
    )
    protected String senderIdentifier;

    @XmlAttribute(
            name = "originatorId"
    )
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(
            name = "originatorId"
    )
    protected String originatorId;

    @XmlAttribute(
            name = "senderRole"
    )
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(
            name = "senderRole"
    )
    protected String senderRole;

    @XmlAttribute(
            name = "messageID"
    )
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(
            name = "messageID"
    )
    protected String messageID;

    public MessageTypeSelector() {
    }

    public String getNamespaceURI() {
        return this.namespaceURI;
    }

    public void setNamespaceURI(String value) {
        this.namespaceURI = value;
    }

    public String getRootElementLocalName() {
        return this.rootElementLocalName;
    }

    public void setRootElementLocalName(String value) {
        this.rootElementLocalName = value;
    }

    public XMLGregorianCalendar getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    public String getNodeID() {
        return this.nodeID;
    }

    public void setNodeID(String value) {
        this.nodeID = value;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String value) {
        this.id = value;
    }

    // UNP attrs
    public String getSenderIdentifier() {
        return this.senderIdentifier;
    }

    public void setSenderIdentifier(String value) {
        this.senderIdentifier = value;
    }

    public String getOriginatorId() {
        return this.originatorId;
    }

    public void setOriginatorId(String value) {
        this.originatorId = value;
    }

    public String getSenderRole() {
        return this.senderRole;
    }

    public void setSenderRole(String value) {
        this.senderRole = value;
    }

    public String getMessageID() {
        return this.messageID;
    }

    public void setMessageID(String value) {
        this.messageID = value;
    }
}
