//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.22 at 01:59:37 PM MSK 
//


package com.nineone.smev.schemas;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nineone.smev.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nineone.smev.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExchangePackage }
     * 
     */
    public ExchangePackage createExchangePackage() {
        return new ExchangePackage();
    }

    /**
     * Create an instance of {@link ExchangePackage.MtomList }
     * 
     */
    public ExchangePackage.MtomList createExchangePackageMtomList() {
        return new ExchangePackage.MtomList();
    }

    /**
     * Create an instance of {@link ExchangePackage.Content }
     * 
     */
    public ExchangePackage.Content createExchangePackageContent() {
        return new ExchangePackage.Content();
    }

    /**
     * Create an instance of {@link ExchangePackage.MtomList.MtomFile }
     * 
     */
    public ExchangePackage.MtomList.MtomFile createExchangePackageMtomListMtomFile() {
        return new ExchangePackage.MtomList.MtomFile();
    }

}
